### ISSUE TITLE
Project Proposal Final Draft (due 9/16)

### ISSUE THREAD

**Issue by saltzmanj** [saltzmanj/keyboardguys#2]
Due 9/14 11:59 PM:

Follows #1 

Here's the notes from class:

### Background
	- Why you chose said project
	- What's been done in the past
	- Your "spin" or contribution

### Description of Project (Detailed)
	- What it is
	- How it works
	- Anticipated problems
	- Block Diagrams (schematics for subsection)

### Deliverables
	- What your are going to build: detailed!
		- Board
		- Interfaces
		- Power Sources

### Timeline
	- Gantt Chart
	- Serial + Parallel Tasks
	- Who does what, primary and secondary
	- Cognizant of dates discuessed on the first day of class

### Expectations
	- Deliverables
	- Working project of your overall grad
		- If this much works: A
		- Else if this much works: B

Word .docx format: track changes must be turned on

References: IEEE Style

**Comment by MrBitSage** [comment]
![keyboardguys_gantt](https://cloud.githubusercontent.com/assets/7970325/18520631/a5f23d7e-7a76-11e6-8809-742300f9ddf5.png)

**Comment by saltzmanj** [comment]
Due date changed to 9/16

**Comment by saltzmanj** [comment]
@MrBitSage can you post the gantt chart file in the Google Drive folder?

**Comment by saltzmanj** [comment]
Tasks per the announcement email... this list replaces the one earlier in this thread.

## Things to do before Friday

**Everyone**
- [ ] Add 4-6 more references throughout

@saltzmanj
- [ ] Expand on engineering challenges section
- [ ] Submit Friday evening

@MrBitSage
- [ ] Expand on timeline section
- [ ] Post the Gantt chart file in Google Drive

@arlieu 
- [ ] Expand on note indication section

**Comment by MrBitSage** [comment]
Timeline section update (each bullet is a paragraph since we can't indent stuff here):

- There are several key components in our project that need to work in concert to deliver the experience we are aiming for. Luckily, these components can be built and tested independently of one another. We have taken these sub-systems and divided them up amongst the three of us.
- Jake will be handling the PCBs, including how to power them and how they will communicate with the myRIO. He will start off by researching, acquiring, and testing possible different components for the PCBs on a bread board. Once he has finalized the components, he will need to design the PCBs that will hold the components and must fit into the keyboard we use.
This process will have to be an iterative one that slowly increases in how many components we manufacture at once since we don’t want to have scrap upwards of 80 small PCBs each iteration. Jason will be working with Jake to configure how the microcontroller will interface with the LEDs on the PCBs.
- Jason will also be implementing the note capturing / machine vision system. He will need to start by formalizing what inputs the system will be expecting. He will need to consider where to place fiduciary marks, how much of a page will be imaged at once, how to place guides on the paper for the user that don’t interfere with note recognition down the line. Once these parameters are formalized, he will need to research, acquire, and test cameras to determine which one delivers the best representation of the flat pages we will be working with. Once the input parameters have been formalized and a camera selected, he will then implement the actual machine vision using the myRIO’s existing imaging libraries. As he finishes up these tasks, he will start working with Avery to get the note recognition as efficient as possible by leveraging the FPGA chip in the myRIO.
- Meanwhile, Avery will be working on implementing said note recognition. He will need to work on this in a very iterative manner with each iteration requiring him to either implement or improve a machine learning algorithm, train the algorithm, and then test its efficacy. He will need to work out a solution to one of our main problems during this time: where to get enough data to train the algorithm. Once he has solved that problem and gotten an algorithm that can detect a basic C-major scale at 120 bpm, he will work on improving the algorithm as much as possible to account for as many input possibilities as time permits. After the notes are being accurately recognized, he will need to determine how to store the note information in a way that it can be processed and output to the LEDs.
- Lastly, we will all need to work together to synthesize the individual systems into a single working product. This will involve us acquiring the keyboard we will be using, installing the customizations, interfacing with each other’s components and debugging the final machine. We anticipate that there will be many things we will be surprised by so we have set an early date for when each of our parts need to be completed and synthesis needs to start. Details on each of the tasks and approximate due dates can be seen in the Gantt chart below.

**Comment by saltzmanj** [comment]
Submitted! The copy we submitted is here. I'll convert this to markdown and put it in the wiki section.

[20160916_Capstone_Proposal_final.docx](https://github.com/saltzmanj/keyboardguys/files/477816/20160916_Capstone_Proposal_final.docx)

**Comment by MrBitSage** [comment]
Final Submission:
[20160916_Capstone_Proposal_final.docx](https://github.com/saltzmanj/keyboardguys/files/477959/20160916_Capstone_Proposal_final.docx)

**Comment by saltzmanj** [comment]
Everything was converted to Markdown and put on the Wiki, the page is here: https://github.com/saltzmanj/keyboardguys/wiki/Project-Proposal
